// flow-typed signature: 74974a4b45f855b08ff46a9cf6da6226
// flow-typed version: <<STUB>>/string-length_v^2.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-length'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-length' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'string-length/index' {
  declare module.exports: $Exports<'string-length'>;
}
declare module 'string-length/index.js' {
  declare module.exports: $Exports<'string-length'>;
}
